### ISSUE TITLE
Man muss zweimal auf senden drücken

### ISSUE THREAD

**Issue by vsisevka** [naelgithub/MyMessenger#6]
Beim Versenden einer Nachricht muss zweimal auf den senden Button gedrückt werden. (Evtl kein Fehler der Implementierung sondern des Emulators)

**Comment by naelgithub** [comment]
Ja genau es ist Emulator-Funktion. so dass bei erste Druck bekommt den Send-Button den Focus und beim zweite Druck wird das Click-Event von Send-Button gefeuert. 
Nael
